# Site settings
title: Bob Cao
email: bob.f.cao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog, all ramblings are mine not my employer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bobintornado.github.io" # the base hostname & protocol for your site
twitter_username: bobintornado
github_username:  bobintornado

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
